// ─── SUBTITLE TEMPLATES ────────────────────────────────────────────────
// Each template defines how animated captions look on screen
// animationType: "word_highlight" | "word_pop" | "fade_word" | "karaoke" | "outline_pop" | "box_fill" | "split_line"

export const SUBTITLE_TEMPLATES = {
  classic_white: {
    id: "classic_white",
    name: "Classic White",
    number: "01",
    category: "Basic",
    desc: "Subtítulo blanco limpio, fade por palabra",
    fontFamily: "'Inter', sans-serif",
    fontWeight: "700",
    textTransform: "none",
    fontSize: 22,
    color: "#FFFFFF",
    highlightColor: null,
    highlightBg: null,
    stroke: null,
    shadow: "0 2px 12px rgba(0,0,0,0.95)",
    animationType: "fade_word",
    position: "abajo",
    bgStyle: null,
    previewBg: "linear-gradient(160deg, #1c1c1c 0%, #0a0a0a 100%)",
    previewAccent: "#FFFFFF",
  },
  impact_highlight: {
    id: "impact_highlight",
    name: "Impact Highlight",
    number: "02",
    category: "Contemporary",
    desc: "Palabra activa en amarillo, resto blanco — estilo viral",
    fontFamily: "'Inter', sans-serif",
    fontWeight: "900",
    textTransform: "uppercase",
    fontSize: 26,
    color: "#FFFFFF",
    highlightColor: "#FFE600",
    highlightBg: null,
    stroke: null,
    shadow: "0 3px 20px rgba(0,0,0,0.98)",
    animationType: "word_highlight",
    position: "abajo",
    bgStyle: null,
    previewBg: "linear-gradient(160deg, #1a1a00 0%, #0a0a00 100%)",
    previewAccent: "#FFE600",
  },
  reels_box: {
    id: "reels_box",
    name: "Reels Box",
    number: "03",
    category: "Contemporary",
    desc: "Fondo sólido por palabra, estilo CapCut / Instagram",
    fontFamily: "'Inter', sans-serif",
    fontWeight: "800",
    textTransform: "none",
    fontSize: 22,
    color: "#000000",
    highlightColor: "#000000",
    highlightBg: "#FFFFFF",
    stroke: null,
    shadow: "none",
    animationType: "box_fill",
    position: "abajo",
    bgStyle: "box",
    previewBg: "linear-gradient(160deg, #1a1a1a 0%, #0a0a0a 100%)",
    previewAccent: "#FFFFFF",
  },
  orange_fire: {
    id: "orange_fire",
    name: "Orange Fire",
    number: "04",
    category: "Contemporary",
    desc: "Naranja vibrante con pop por palabra",
    fontFamily: "'Inter', sans-serif",
    fontWeight: "900",
    textTransform: "uppercase",
    fontSize: 24,
    color: "#FFFFFF",
    highlightColor: "#FF6A00",
    highlightBg: null,
    stroke: null,
    shadow: "0 2px 20px rgba(255,106,0,0.5), 0 2px 8px rgba(0,0,0,0.9)",
    animationType: "word_pop",
    position: "abajo",
    bgStyle: null,
    previewBg: "linear-gradient(160deg, #1a0800 0%, #0a0500 100%)",
    previewAccent: "#FF6A00",
  },
  cinematic_serif: {
    id: "cinematic_serif",
    name: "Cinematic Serif",
    number: "05",
    category: "Hollywood",
    desc: "Serif elegante, aparición por línea completa",
    fontFamily: "'Georgia', serif",
    fontWeight: "400",
    textTransform: "none",
    fontSize: 20,
    color: "#F5F0E8",
    highlightColor: "#D4AF70",
    highlightBg: null,
    stroke: null,
    shadow: "0 4px 32px rgba(0,0,0,0.98)",
    animationType: "fade_word",
    position: "abajo",
    bgStyle: null,
    previewBg: "linear-gradient(160deg, #100d08 0%, #06050300 100%)",
    previewAccent: "#D4AF70",
  },
  neon_glow: {
    id: "neon_glow",
    name: "Neon Glow",
    number: "06",
    category: "Hollywood",
    desc: "Texto con glow neón, letra a letra",
    fontFamily: "'Inter', sans-serif",
    fontWeight: "800",
    textTransform: "uppercase",
    fontSize: 22,
    color: "#FFFFFF",
    highlightColor: "#A78BFA",
    highlightBg: null,
    stroke: null,
    shadow: "0 0 20px #A78BFA, 0 0 40px #A78BFA66, 0 2px 10px rgba(0,0,0,0.9)",
    animationType: "word_highlight",
    position: "abajo",
    bgStyle: null,
    previewBg: "linear-gradient(160deg, #0a0016 0%, #050008 100%)",
    previewAccent: "#A78BFA",
  },
  outline_bold: {
    id: "outline_bold",
    name: "Outline Bold",
    number: "07",
    category: "Basic",
    desc: "Stroke negro grueso, word pop",
    fontFamily: "'Inter', sans-serif",
    fontWeight: "900",
    textTransform: "none",
    fontSize: 24,
    color: "#FFFFFF",
    highlightColor: "#FFFFFF",
    highlightBg: null,
    stroke: "4px #000000",
    shadow: "none",
    animationType: "word_pop",
    position: "abajo",
    bgStyle: null,
    previewBg: "linear-gradient(160deg, #1a1a1a 0%, #0a0a0a 100%)",
    previewAccent: "#FFFFFF",
  },
  split_bar: {
    id: "split_bar",
    name: "Split Bar",
    number: "08",
    category: "Hollywood",
    desc: "Barra horizontal, texto al costado — estilo documental",
    fontFamily: "'Inter', sans-serif",
    fontWeight: "700",
    textTransform: "uppercase",
    fontSize: 18,
    color: "#FFFFFF",
    highlightColor: "#FF6A00",
    highlightBg: null,
    stroke: null,
    shadow: "0 2px 12px rgba(0,0,0,0.9)",
    animationType: "split_line",
    position: "abajo",
    bgStyle: "bar",
    previewBg: "linear-gradient(160deg, #0a0a10 0%, #050508 100%)",
    previewAccent: "#FF6A00",
  },
};

// legacy text templates (for title overlays, not subtitles)
export const TEMPLATES = {
  mono_cinema: {
    id: "mono_cinema", name: "MONO CINEMA", number: "01",
    desc: "Sans-serif uppercase, fade + slide",
    fontFamily: "'Inter', sans-serif", fontWeight: "800",
    textTransform: "uppercase", letterSpacing: "0.18em",
    animationType: "fade_slide", layout: "single",
    previewBg: "linear-gradient(160deg, #1a1a1a 0%, #0a0a0a 100%)",
    previewText1: "ARTISTA", previewColor: "#FFFFFF",
  },
  editorial_noir: {
    id: "editorial_noir", name: "EDITORIAL NOIR", number: "02",
    desc: "Serif + sans, side reveal",
    fontFamily: "'Georgia', serif", fontWeight: "400",
    textTransform: "none", letterSpacing: "0.06em",
    animationType: "side_reveal", layout: "double",
    previewBg: "linear-gradient(160deg, #141010 0%, #0d0808 100%)",
    previewText1: "Editorial", previewText2: "NOIR",
    previewColor: "#F5F0E8", previewColor2: "#CC8866",
  },
  impact_subtitles: {
    id: "impact_subtitles", name: "IMPACT PRO", number: "03",
    desc: "Bold, word-by-word, highlight",
    fontFamily: "'Inter', sans-serif", fontWeight: "900",
    textTransform: "uppercase", letterSpacing: "0.02em",
    animationType: "word_pop", layout: "subtitle",
    previewBg: "linear-gradient(160deg, #0f0f1a 0%, #080810 100%)",
    previewText1: "IMPACT", previewColor: "#FFFFFF",
  },
  triple_layer: {
    id: "triple_layer", name: "TRIPLE LAYER", number: "04",
    desc: "3-tier hierarchy, staggered",
    fontFamily: "'Georgia', serif", fontWeight: "700",
    textTransform: "none", letterSpacing: "0.05em",
    animationType: "stagger", layout: "triple",
    previewBg: "linear-gradient(160deg, #0f1a14 0%, #080d0a 100%)",
    previewText1: "Triple", previewText2: "CINEMA",
    previewColor: "#E8F5EE", previewColor2: "#66CC99",
  },
  fashion_glitch: {
    id: "fashion_glitch", name: "FASHION GLITCH", number: "05",
    desc: "Micro-glitch, reflection",
    fontFamily: "'Inter', sans-serif", fontWeight: "300",
    textTransform: "uppercase", letterSpacing: "0.22em",
    animationType: "glitch", layout: "single",
    previewBg: "linear-gradient(160deg, #1a0a1a 0%, #0d050d 100%)",
    previewText1: "GLITCH", previewColor: "#EE88FF",
  },
};

export const STOCK_VIDEOS = [
  {
    label: "Urban Night",
    url: "https://assets.mixkit.co/videos/preview/mixkit-city-at-night-seen-from-a-rooftop-9394-large.mp4",
    poster: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=400&h=711&fit=crop",
    orientation: "vertical",
  },
  {
    label: "Studio Dark",
    url: "https://assets.mixkit.co/videos/preview/mixkit-musician-in-a-recording-studio-5453-large.mp4",
    poster: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=400&h=711&fit=crop",
    orientation: "horizontal",
  },
  {
    label: "Slow Fashion",
    url: "https://assets.mixkit.co/videos/preview/mixkit-young-woman-walking-in-a-forest-3591-large.mp4",
    poster: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=711&fit=crop",
    orientation: "vertical",
  },
];

// Sample subtitle lines to demo in preview
export const DEMO_SUBTITLE_LINES = [
  "Cada palabra que dices",
  "cuenta una historia",
  "que el mundo necesita escuchar",
];